### ISSUE TITLE
JPG quality

### ISSUE THREAD

**Issue by photopea** [vigata/petitoJPEG#2]
Hi, could you improve the quality a bit at the same size?  The computation time would probably increase, but it is ok.

Here is a picture converted to JPG with Canvas.toDataURL("jpg") in Chrome (raptor.jpg) and with your tool (raptor2.jpg). Your picture is much larger, while having much worse quality.

[raptor.png](https://user-images.githubusercontent.com/15955558/45909767-3699dd00-be04-11e8-8aaa-3ab79bee5a21.png) - 157 kB
[raptor.jpg](https://user-images.githubusercontent.com/15955558/45909768-3699dd00-be04-11e8-9f72-76ab2ba9cdee.jpg) - 9.7 kB
[raptor2.jpg](https://user-images.githubusercontent.com/15955558/45909766-3699dd00-be04-11e8-9fc5-c85ece68b3d4.jpg) - 14.7 kB

**Comment by vigata** [comment]
The likely reason for the bigger size and worse compression is that petitoJPEG is only producing 4:4:4 color format.
I'll introduce 4:2:0 support into petitoJPEG which will improve visual quality and should also have minimal impact in computation time. Stay tuned.

**Comment by vigata** [comment]
Hello. I've updated the library with 4:2:0 support and in my testing it does make the encoding of the raptor.png image you provided much better with negligible performance impact. Is still not as good as Canvas.toDataURL() but closer. It probably requires further optimization of quantization and huffman tables.

API has not changed and it should now automatically switch between 4:2:0 and 4:4:4 depending on quality setting. There's an API to force either, please see README.

**Comment by photopea** [comment]
Could you please update the demo, too? http://godromo.com/petitojpeg

**Comment by vigata** [comment]
Demo has been updated. Thanks for the suggestion.

**Comment by photopea** [comment]
Alberto, you are amazing! You just made the best Javascript JPG encoder that exists. 

Would you like to go further, to beat the Canvas.toDataURL()? I think, that a custom JPG encoder is really useful, as it may have more flexibility over Canvas (e.g. adding metadata to JPG files), and if it beats Canvas, it would be absolutely astonishing.

BTW. I made https://github.com/photopea/UPNG.js , which is, I believe, the best PNG minifier in the world (not restricted to Javascript) :D  You could use my quantization, which is quite advanced (it is not the "standard" iterative algorithm, but a faster one, that uses KD trees).

**Comment by vigata** [comment]
I'd like to improve the quality of the encoder if there's interest. Probably at this point a hard look into customized quant tables and huffman tables would work. Also Google has done a lot of work recently in this space with guetzli (https://github.com/google/guetzli) , so maybe some ideas can be incorporated here.

I'll definitely take a look at your PNG encoder!

**Comment by photopea** [comment]
I don't think Guetzli is a good example of a JPG compressor of this class. Similar to Zopfli, Guetzli exhaustively looks for a good compression, which takes a lot of time (1 minute per megapixel).

Let me start another issue regarding the quality of compression. You can look at it whenever you have time, you don't have to hurry :)
