### ISSUE TITLE
Same Image, Different ImageData on 2 Computers

### ISSUE THREAD

**Issue by RickyYoder** [vigata/petitoJPEG#4]
Great encoder! Does what I need. But I'm having an issue in consistency somehow.
My web page is using the encoder as a Worker. My Samsung Chromebook Pro is logging 26562 bytes written, and my Lenovo x230 Windows laptop is logging 27586. The image size is correct on both laptops, 1125x675.

I have 2 dots on the canvas. 1 green dot on the left hand side, and one red dot on the right hand side. The red dot is completely omitted from the encoded JPG on the Chromebook, but not on the Lenovo X230.

Below is a link on my website. I will keep this web page live and not make any changes.

Open the console and type "encode()". The Proof link in the top right corner will let you download the resulting JPEG afterwards.

[](http://xbit.x10host.com/editor2.php)

**Comment by vigata** [comment]
Are you using different browsers? The only reason why byte count would be different is because the browser is passing a slightly different image to the encoder. Otherwise pipelines are identical and should produce bitexact streams
